# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time
import sys
import trainingui
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 750, 405))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(:/newPrefix/blackback.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.TrainMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.TrainMenuButton.setGeometry(QtCore.QRect(80, 300, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Zaandam")
        self.TrainMenuButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/neural-network-removebg-preview (1).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TrainMenuButton.setIcon(icon)
        self.TrainMenuButton.setIconSize(QtCore.QSize(92, 46))
        self.TrainMenuButton.setAutoDefault(False)
        self.TrainMenuButton.setDefault(False)
        self.TrainMenuButton.setFlat(False)
        self.TrainMenuButton.setObjectName("TrainMenuButton")
        self.drawMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.drawMenuButton.setGeometry(QtCore.QRect(510, 300, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Zaandam")
        self.drawMenuButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/pencil.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drawMenuButton.setIcon(icon1)
        self.drawMenuButton.setIconSize(QtCore.QSize(50, 46))
        self.drawMenuButton.setObjectName("drawMenuButton")
        self.label.raise_()
        self.drawMenuButton.raise_()
        self.TrainMenuButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.TrainMenuButton.clicked.connect(self.opneTrainingWin)
        self.drawMenuButton.clicked.connect(self.canvasWindow)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def canvasWindow(self):
        subprocess.call(["python","canvasWindow.py"])

    def opneTrainingWin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = trainingui.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TrainMenuButton.setText(_translate("MainWindow", "Train Network"))
        self.drawMenuButton.setText(_translate("MainWindow", "Test Network  "))
import mainBack_rc


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)

    # Create splashscreen
    splash_pix = QtGui.QPixmap('logo-color.jpg')
    splash = QtWidgets.QSplashScreen(splash_pix, QtCore.Qt.WindowStaysOnTopHint)
    # add fade to splashscreen 
    opaqueness = 0.0
    step = 0.025
    splash.setWindowOpacity(opaqueness)
    splash.show()
    while opaqueness <= 1:
        splash.setWindowOpacity(opaqueness)
        time.sleep(step) # Gradually appears
        opaqueness+=step
    time.sleep(3) # hold image on screen for a while
    splash.close() # close the splash screen

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
